channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pip
  - python
  - cython
  - astropy
  - scipy
  - pandas
  - emcee
  - corner
  - h5py
  - pip:
      - matplotlib
      - orbitize
